name: 69Yun Auto Checkin

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *' # 北京时间凌晨 03:00

# 添加全局环境变量，强制使用 Node.js 24 运行 Actions
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Checkin Script
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          USER1: ${{ secrets.USER1 }}
          PASS1: ${{ secrets.PASS1 }}
        run: python 69yun.py
